ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 9 '+L8DATA/cropsnew/redo09.log' SIZE 250M reuse;
ALTER DATABASE ADD LOGFILE THREAD 2 GROUP 10 '+L8DATA/cropsnew/redo10.log' SIZE 250M reuse;
ALTER DATABASE ADD LOGFILE THREAD 3 GROUP 11 '+L8DATA/cropsnew/redo11.log' SIZE 250M reuse;
ALTER DATABASE ADD LOGFILE THREAD 4 GROUP 12 '+L8DATA/cropsnew/redo12.log' SIZE 250M reuse;


ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 4 '/data/oradata/mdsops/redo04.log' SIZE 150 reuse;
ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 5 '/data/oradata/mdsops/redo05.log' SIZE 150 reuse;
ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 6 '/data/oradata/mdsops/redo06.log' SIZE 150 reuse;
ALTER DATABASE ADD LOGFILE THREAD 1 GROUP 7 '/data/oradata/mdsops/redo07.log' SIZE 150 reuse;

ALTER SYSTEM SWITCH LOGILFE;
ALTER SYSTEM CHECKPOINT;
ALTER DATABASE DROP LOGFILE GROUP 1;
ALTER DATABASE DROP LOGFILE GROUP 2;
ALTER DATABASE DROP LOGFILE GROUP 3;